# Merge into your pyproject.toml

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
sqlalchemy = "^2.0.32"
psycopg = {version = "^3.2.1", extras=["binary"]}
pydantic = "^2.8.2"
pydantic-settings = "^2.4.0"
boto3 = "^1.34.162"
mlflow = "^2.14.3"
streamlit = "^1.37.1"
bokeh = "^3.5.0"
seaborn = "^0.13.2"
fastapi = "^0.115.0"
uvicorn = "^0.30.5"
pyspark = "^3.5.1"  # optional, only if you use Spark

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.9"
black = "^24.10.0"
mypy = "^1.11.2"
bandit = "^1.7.9"
pytest = "^8.3.2"
hypothesis = "^6.112.3"
pytest-benchmark = "^4.0.0"
sphinx = "^7.4.7"
furo = "^2024.8.6"
myst-parser = "^3.0.1"
sphinxcontrib-mermaid = "^0.9.2"
sphinx-autodoc-typehints = "^2.4.4"
pyan3 = "^1.2.0"
pylint = "^3.2.6"  # for pyreverse
pre-commit = "^3.8.0"
graphviz = "^0.20.3"
