name: ci-augment
on:
  pull_request:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
      - name: Install project
        run: poetry install --with dev
      - name: Lint/Type/Tests/Docs/Diagrams
        run: |
          make -f Makefile ci-check
      - name: Upload docs HTML
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html
