name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v4

      # Fast Conda with micromamba; install rdkit/openmm from conda-forge
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: stickit-ci
          create-args: >-
            python=${{ matrix.python-version }}
            -c conda-forge
            rdkit openmm openff-toolkit numpy pip
          cache-environment: true
          cache-downloads: true

      - name: Install Poetry
        run: pip install poetry==1.8.3

      - name: Install package (no building Conda pkgs)
        run: poetry install --with dev

      - name: Run tests
        run: poetry run pytest -q

      - name: Build docs
        run: |
          poetry run sphinx-build -b html docs docs/_build/html
        # Save docs as artifact so we can inspect on PRs
      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html

