# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    defaults:
      run:
        shell: bash -el {0}   # keep conda activation across steps

    steps:
      - uses: actions/checkout@v4

      - name: Cache conda pkgs (optional)
        uses: actions/cache@v4
        with:
          path: ~/.conda/pkgs
          key: ${{ runner.os }}-condapkgs-${{ hashFiles('environment.yml') }}
          restore-keys: ${{ runner.os }}-condapkgs-

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
          use-mamba: true

      # If environment.yml + requirements*.txt are committed, we can create/update directly.
      - name: Create/Update env from environment.yml
        run: |
          conda env create -n stickit-ci -f environment.yml || \
          conda env update  -n stickit-ci -f environment.yml --prune
          conda activate stickit-ci
          python -V

      - name: Install Poetry
        run: |
          conda activate stickit-ci
          pip install poetry==2.0.1

      - name: Guard: lock & requirements sanity
        run: |
          conda activate stickit-ci
          poetry lock --check
          ! grep -R "@ file:///" -n . || (echo "Found file:// refs; fix requirements.txt" && exit 1)

      # Build the distribution we will test
      - name: Build wheel/sdist
        run: |
          conda activate stickit-ci
          poetry build
          ls -l dist/

      # Install the built wheel into the env (no deps: conda/pip already installed them)
      - name: Install wheel
        run: |
          conda activate stickit-ci
          WHEEL=$(ls dist/*.whl | head -n1)
          pip install --no-deps "$WHEEL"

      - name: Quick import smoke
        run: |
          conda activate stickit-ci
          python - <<'PY'
          import stickit, rdkit, openmm
          from openff.toolkit import __version__ as off_ver
          print("stickit", getattr(stickit, "__version__", "n/a"))
          print("rdkit", rdkit.__version__)
          print("openmm", openmm.__version__)
          print("openff", off_ver)
          PY

      - name: Tests
        run: |
          conda activate stickit-ci
          pytest -q

      - name: Build docs
        run: |
          conda activate stickit-ci
          sphinx-build -b html docs docs/_build/html

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
