name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]

    # Make the micromamba env active for all run steps
    defaults:
      run:
        shell: micromamba-shell {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up micromamba (+conda-forge, cached)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: stickit-ci
          create-args: >-
            -c conda-forge
            python=${{ matrix.python-version }}
            rdkit
            openmm
            openff-toolkit
            numpy
            pip
          cache-environment: true
          cache-downloads: true
          init-shell: bash
          generate-run-shell: true

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.1
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Cache Poetry downloads
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: poetry-cache-${{ runner.os }}-

      - name: Install package (locked & synchronized)
        run: poetry install --with dev --sync

      - name: Check lock is up-to-date
        run: poetry lock --check

      - name: Quick import smoke (rdkit/openmm)
        run: |
          python - <<'PY'
          import rdkit, openmm, openff
          print('rdkit', rdkit.__version__)
          print('openmm', openmm.__version__)
          print('openff', openff.__version__)
          PY

      - name: Run tests
        run: poetry run pytest -q

      - name: Build docs
        run: poetry run sphinx-build -b html docs docs/_build/html

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html

